
baseURL = '/'
languageCode = 'en-us'
title = 'Katzenpost'
contentDir = 'content/en'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false
enableMissingTranslationPlaceholders = true
enableRobotsTXT = true
enableGitInfo = true

[taxonomies]
  tag = 'tags'
  category = 'categories'
  pygmentsCodeFences = true
  pygmentsUseClasses = false
  pygmentsUseClassic = false
  pygmentsStyle = 'tango'

[permalinks]
  [page]
    pages = "/:slug"
  [section]
    blog = "/blog/:slug"

[imaging]
  resampleFilter = "CatmullRom"
  quality = 75
  anchor = "smart"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    [languages.en.params]
      title = "Katzenpost"
      description = "A next generation privacy preserving mixnet with post-quantum cryptography"

[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"
