baseURL: "/"
title: "Katzenpost"
contentDir: "content/en"
defaultContentLanguage: "en"
defaultContentLanguageInSubdir: false
enableMissingTranslationPlaceholders: true
enableRobotsTXT: true
enableGitInfo: true
taxonomies:
  tag: "tags"
  category: "categories"
  pygmentsCodeFences: true
  pygmentsUseClasses: false
  pygmentsUseClassic: false
  pygmentsStyle: "tango"
permalinks:
  page:
    pages: "/:slug"
  section: 
    docs: "/:slug"
    blog: "/:slug"

imaging:
  resampleFilter: "CatmullRom"
  quality: 75
  anchor: "smart"
languages:
  en:
    languageName: "English"
    weight: 1
    params:
      title: "Katzenpost"
      description: "A next generation privacy preserving mixnet with post-quantum cryptography"

markup:
  goldmark:
    parser:
      attribute:
        block: true
    renderer:
      unsafe: true
  highlight:
    style: "tango"
outputs:
  section:
    - "HTML"
    - "print"
    - "RSS"
    - "DecapCMSConfig"
module:
  hugoVersion:
    extended: true
    min: "0.110.0"
  imports:
    - path: "github.com/google/docsy"
      disable: false
    - path: "github.com/google/docsy/dependencies"
      disable: false
    - path: "github.com/hugomods/decap-cms"
