main:
  - name: "Values"
    weight: 10
    url: "/moral-character"
  - name: "Admin Guide"
    weight: 20
    url: "/admin_guide"
  - name: "Code"
    weight: 50
    url: "https://github.com/katzenpost"

