copyright: "Katzenpost"
privacy_policy: 'https://katzenpost.network/privacy'
version_menu: "Releases"
archived_version: false
version: '0.0'
url_latest_version: 'https://katzenpost.network'
github_repo: 'https://github.com/katzenpost/website'
github_project_repo: 'https://github.com/katzenpost/katzenpost'
github_branch: "main"
algolia_docsearch: false
offlineSearch: false
prism_syntax_highlighting: false

taxonomy:
  taxonomyCloud:
    - "tags"
    - "categories"
  taxonomyCloudTitle:
    - "Browse by Tag"
    - "Categories"
  taxonomyPageHeader:
    - "tags"
    - "categories"

ui:
  breadcrumb_disable: false
  footer_about_disable: false
  navbar_logo: true
  navbar_translucent_over_cover_disable: false
  sidebar_menu_compact: false
  sidebar_search_disable: false
  feedback:
    enable: true
    'yes': >-
      Glad to hear it! Please <a
      href="https://github.com/katzenpost/website/issues/new">tell us how we can
      improve</a>.
    'no': >-
      Sorry to hear that. Please <a
      href="https://github.com/katzenpost/website/issues/new">tell us how we can
      improve</a>.
  readingtime:
    enable: false
links:
  user:
    - name: "User mailing list"
      url: "https://lists.mixnetworks.org/listinfo/katzenpost"
      icon: "fa fa-envelope"
      desc: "Discussion and help from your fellow users"
  developer:
    - name: "GitHub"
      url: "https://github.com/katzenpost/katzenpost"
      icon: "fab fa-github"
      desc: "Development takes place here!"
    - name: "IRC #katzenpost (OFTC)"
      url: "irc://irc.oftc.net/#katzenpost"
      icon: "fab fa-irc"
      desc: "Chat with other project developers"
    - name: "Developer mailing list"
      url: "https://lists.mixnetworks.org/listinfo/katzenpost"
      icon: "fa fa-envelope"
      desc: "Discuss development issues around the project"

decap_cms:
  media_folder: "static/images/uploads"
  public_folder: "/images/uploads"
  publish_mode: "editorial_workflow"
  search: true
